### ISSUE TITLE
Adblockers (e.g. uBlock Origin) block wasm files

### ISSUE THREAD

**Issue by floryst** [InsightSoftwareConsortium/itk-js#123]
Adblockers (e.g. uBlock Origin) that use the EasyPrivacy list will block all wasm files fetched via xmlhttprequest.

Glance reference: https://github.com/Kitware/pv-web-viewer/issues/62

**Comment by thewtex** [comment]
This is interesting. I use uBlock Origin, too -- I have verified the behavior, but it is new to me -- they must have added the block recently.

**Comment by thewtex** [comment]
I have reported the issue on the [EasyList forum](https://forums.lanik.us/).

**Comment by floryst** [comment]
I think it's b/c people use github.io as hosting for wasm-based cryptocoin miners, so EasyList maintainers decided a blanket wasm block on github.io is best.

**Comment by thewtex** [comment]
@floryst That's interesting -- hopefully the EasyList folks realize that wasm can be used for good :-).

Regardless, #126 addresses this (released in itk.js 9.1.0), since now we inline the WebAssembly in a `*.js` file, so there is no more `*.wasm` file to be blocked.

CC: @aylward
