### ISSUE TITLE
Installing itk-js

### ISSUE THREAD

**Issue by ericdebleumortier** [InsightSoftwareConsortium/itk-js#137]
Hi, 

When I try to install itk through node & webpack, this is failing. The folder created is strange, it contains every module on the root, no package.json, no build file, nothing usefull.

In unpkg.com itself an error is displayed (https://unpkg.com/itk@9.1.2/dist/itk.js)
`Cannot find "/dist/itk.js" in itk@9.1.2`

Is it the normal behaviour? Am I missing the whole thing?

**Comment by thewtex** [comment]
Install the itk.js node package with, and:

```
npm install --save itk
```

This installs the built package. It contains a `package.json`, `LICENSE`, `README.md`, the JavaScript modules that will be used by dependent project sources, along with Emscripten module image IO, mesh IO, related web workers. The latter are pre-built, so you only need the standard `node` and `npm` to use the package in a dependent project.

That is not the correct path in unpkg, but the package would not be used in this way from unpkg regardless.

For more information, please see the documentation:

https://insightsoftwareconsortium.github.io/itk-js/examples/
