### ISSUE TITLE
Error in ImageIO.worker.js ???

### ISSUE THREAD

**Issue by yh3ds** [InsightSoftwareConsortium/itk-js#140]
Hello,
we are running itk-js with webpack

After sweating a lot, we finally manage to call readImageFile with a blob containing the image as parameter

Unfortunately, we try it with .jpg / tif / png and no one is working.
Looking at the result of the callback, we get a rejected Promise with a different reason depending on the image file type.

Digging into : itk/WebWorkers/ImageIO.worker.js
It seems the error  are coming from the methods implemented in the file ... 

Could you have a look at it ?

Thank you very much

PS : here is the log of the error messages with the different image file type

----------------
JPG / PNG
----------------

Promise { "rejected" }
​	<state>: "rejected"
​	<reason>: {…}
​​		message: "e is undefined"

----------------
TIF
----------------

Promise { "rejected" }
​	<state>: "rejected"
​	<reason>: {…}
​​		message: "Could not read file: /work/"

**Comment by joaosausen** [comment]
We have a similar issue, but it only happens on firefox and on a particular server, it works locally.

**Comment by thewtex** [comment]
@yh3ds @joaosausen could images please be provided to reproduce the issue? Do you observe the same behavior in the [itk-vtk-viewer](https://kitware.github.io/itk-vtk-viewer/app/)?

**Comment by joaosausen** [comment]
@thewtex I believe our issue is related to the browsers and is a cors issue, we used that file:
https://kitware.github.io/itk-vtk-viewer/app/?fileToLoad=https://cors-anywhere.herokuapp.com/http://jupiterweb.ca/w48_flr.nii

Note that we are using the cors-anywhere "proxy", this worked on our tool too.

**Comment by thewtex** [comment]
> https://kitware.github.io/itk-vtk-viewer/app/?fileToLoad=https://cors-anywhere.herokuapp.com/http://jupiterweb.ca/w48_flr.nii

This works for me on Firefox and Chrome.

For CORS issues, please make sure you are using the latest version of itk.js, and there are reference build configurations here:

  https://insightsoftwareconsortium.github.io/itk-js/examples/

**Comment by yh3ds** [comment]
Hello,
after taking the last version, everything seems to work fine.
Thanks a lot for your help.
