### ISSUE TITLE
read dicom with jpeg compress data

### ISSUE THREAD

**Issue by chenkaiC4** [InsightSoftwareConsortium/itk-js#145]
hi, i want to read a dicom with data compressed as jpeg. i find the [daikon.js](https://github.com/rii-mango/Daikon), and use it to get uncompress dicom image, but then, how to use itk-js to read the image, because i use vtk.js too, i know vtk.js depend on itk.js to read such as image, dicom etc.

main code logic is below:

``` js
import itkreadImageDICOMFileSeries from 'itk/readImageDICOMFileSeries';
import vtkHttpDataAccessHelper from 'vtk.js/Sources/IO/Core/DataAccessHelper/HttpDataAccessHelper';

vtkHttpDataAccessHelper.fetchBinary(url).then((arrayBuffer) => {
    const image = daikon.Series.parseImage(new DataView(arrayBuffer));
    if (image === null) {
        console.error(daikon.Series.parserError);
    }

    const rawData = image.getRawData(); // ArrayBuffer

    const filename = `test.dcm`;

    const file = new File([rawData], filename);

    itkreadImageDICOMFileSeries(null, [file])
        .then(({ image: itkImage, webWorker }) => {
            // code not exec here
            // get a Error: Could not read file: /work/test.dcm
        })
})
```

update:

because the raw image data have got, i think i have to create a Image instance, but need a correct ImageType.

https://github.com/InsightSoftwareConsortium/itk-js/blob/f2b16ac4b9097367969dc1ff961037bc43441753/src/Image.js#L4-L23

https://github.com/InsightSoftwareConsortium/itk-js/blob/f2b16ac4b9097367969dc1ff961037bc43441753/src/ImageType.js#L4-L12

but i don't know how to determine the `componentType` `componets` and other input args of constructor `ImageType`.

thanks for your suggestions!

**Comment by thewtex** [comment]
@chenkaiC4 you do not need to use daikon -- use itk.js directly\ and pass it the array buffer.

Here is an example:

https://github.com/Kitware/itk-vtk-viewer/blob/ddc38926657cadfa38280ab4da4e45ca7c482a61/src/processFiles.js#L15-L24

**Comment by thewtex** [comment]
@chenkaiC4 I reproduced the read failure with the daikon.js test dataset -- I will see about fixing the ITK build so JPEG2000 compression is supported.

**Comment by chenkaiC4** [comment]
@thewtex hi, i have create a `Image` instance **manually** which declared at https://github.com/InsightSoftwareConsortium/itk-js/blob/6377e1890d524fa9cf688c21698cfa4cfb6ca02b/src/Image.js#L4 , the raw arraybuffer is get from the `daikon.js`'s `concatenateImageData` method which will reorder the 2D images of dicom and concat them.

relative code shows as follow, it works. But the slicer mode display is not correct. see the two picture.
``` js
      const itkImage = new Image(new ImageType(3, dataType));
      itkImage.size[0] = row;
      itkImage.size[1] = col;
      itkImage.size[2] = dataLength;
      itkImage.spacing[0] = pixelSpacing[1];
      itkImage.spacing[1] = sliceThickness / 2;
      itkImage.spacing[2] = pixelSpacing[0];
      itkImage.direction.setElement(0, 0, 0.0);
      itkImage.direction.setElement(0, 1, -0.0);
      itkImage.direction.setElement(0, 2, -1.0);
      itkImage.direction.setElement(1, 0, 1.0);
      itkImage.direction.setElement(1, 1, 0.0);
      itkImage.direction.setElement(1, 2, 0.0);
      itkImage.direction.setElement(2, 0, 0.0);
      itkImage.direction.setElement(2, 1, -1.0);
      itkImage.direction.setElement(2, 2, 0.0);
      itkImage.data = new Uint16Array(file);

      const imageData = vtkITKHelper.convertItkToVtkImage(itkImage);
```

Follow picture is well display, it display a dicom series not compressed. but the second picture is wrong, the dicom series is the same with the first picture's. i do this just want to test the combination with `daikon.js` and `itk.js`. from the two pictures, the spacing and direction seemd to be wrong. but i don't know how to fix it. 


![image](https://user-images.githubusercontent.com/7543145/50135087-debd2600-02cd-11e9-805b-d65d206ffde9.png)

![image](https://user-images.githubusercontent.com/7543145/50135116-07452000-02ce-11e9-8b26-d5011ed57459.png)




```js
```

**Comment by chenkaiC4** [comment]
@thewtex thanks, i will have a try to fix it. 👍

**Comment by LabbaAwwabi** [comment]
Hi @chenkaiC4 can I email you to ask a lot things about dicom reader?
I need your help

**Comment by chenkaiC4** [comment]
@LabbaAwwabi chenkaiC4@email.com i'm not sure i can solve your problems, just have a try.

**Comment by martinweihrauch** [comment]
Hi!
I just found this thread via google!

What I am trying to accomplish: I have JPEG-LS compressed DICOM images and want to show them in a browser with a certain windowing, which I apply to it.

Do you have - by any chance - any simple code which does that in JS. I. e., start with a DICOM image (e. g. by link) and result in the canvas image with the correct windowing applied? Also stating, exactly which JS libraries to include? I do not need JPEG2000, only JPEG-LS.

Best regards and thanks a lot!

Martin

**Comment by engrussman** [comment]
@martinweihrauch Did you get any solution for JPEG-LS?

**Comment by juanprietob** [comment]
Workaround using [gdcm-js](https://www.npmjs.com/package/gdcm-js)

```
const fs = require('fs');
const gdcm = require("gdcm-js");
const readImageLocalFileSync = require('itk/readImageLocalFileSync.js');

var dicomoriginal = new Uint8Array(fs.readFileSync('compressed.dcm'));
var memfs = [{name: "input.dcm", data: dicomoriginal}]; 
var args = ["-i", "input.dcm", "-o", "output.dcm", "-w"]; 

var result =  gdcm.gdcmconv({MEMFS:memfs,arguments:args});

fs.writeFileSync('temp.dcm', result.MEMFS[0].data)

var in_img = readImageLocalFileSync('temp.dcm');
console.log(in_img)
```

**Comment by juanprietob** [comment]
This reader available in npm [med-img-reader](https://www.npmjs.com/package/med-img-reader) reads compressed DICOM images and returns in the ITK format so it is compatible with VTK.js as well.

**Comment by thewtex** [comment]
Another option here is to add optional support for `readImageDICOMSeries` to use ITK/GDCM, which does have JPEG2000 support (it is currently using ITK/DCMTK without JPEG2000 support).

**Comment by thewtex** [comment]
`itk/readImageFile` and `itk/readImageDICOMSeries` use GDCM under the hood since 12.1.0 (not. that `readImageDICOMSeries`'s interface changed recently), so these issues should be addressed.
