### ISSUE TITLE
Problem with itk-js-cli in Windows 10

### ISSUE THREAD

**Issue by katiamar63** [InsightSoftwareConsortium/itk-js#193]
Hi,
I wanted to compile my first C code in itk.js following your example from https://insightsoftwareconsortium.github.io/itk-js/examples/hello_world_node.html.

I was able to succeed in Mac, but when I tried to build it in Windows, the whole building process from  `npx itk-js build .` was ending just after creating `itk-js-build-env` script in `/web-build` folder.  I attached  Chrome inspector to node and I found that there might be a problem in Node's 'child-process' package, with spawnSync (see below), which is called by itk-js-cli. 
How can I fix it? BTW, I checked my environment and it seems that Docker is working properly, as well as npx and other tools.

![cliproblem](https://user-images.githubusercontent.com/3754848/52815903-dd11a380-306d-11e9-801a-509917f65dc1.PNG)

**Comment by thewtex** [comment]
Thanks for the report. I will investigate.

**Comment by thewtex** [comment]
xref #188

**Comment by thewtex** [comment]
Please try again with `itk>=9.4.1`. On Windows, it is best to use the  *Git Bash* command line. Please re-open if you still encounter issues.
