### ISSUE TITLE
Using itk-js as an external script

### ISSUE THREAD

**Issue by truongleit** [InsightSoftwareConsortium/itk-js#203]
Hi, is it possible to import itk-js as a script tag in HTML file? I am doing a project which is visualization 3D object from a set 2D DICOM with 3 different rendering algorithms. Other 2 methods are now imported by using script tags in my HTML file, so it might be easier for me to integrate VTK and ITK into the project. The reason is that after Webpack minify the original JS file into bundle file, I cannot interact my current code with the function I wrote in the bundle file. Hope to reiceve respond from you soon. Thanks again. @thewtex

**Comment by thewtex** [comment]
We now have a UMD module and an [example](https://insightsoftwareconsortium.github.io/itk-js/examples/umd.html)! :tada:
