### ISSUE TITLE
Dicom tag information?

### ISSUE THREAD

**Issue by EJShim** [InsightSoftwareConsortium/itk-js#210]
Hello,

I am currently trying to convert my original c++(with itk and vtk)-based stand-alone application into

web application.

This is a demo video of what I am doing ( [https://www.youtube.com/watch?v=8ZIxNuMIj9g](https://www.youtube.com/watch?v=8ZIxNuMIj9g) )

I fill there are some limitations when importing DICOM files in web browser compared to using c++  ITK.

Especailly, I do not know how to read DICOM tag information using ITK.js, that is possible by using itk::Metadata thigns in C++.  I am trying to use EMSCripten pipeline module, but it is hard for me to find out how to pass *.dcm files to the pipeline module.
Maybe it would be possible to pass argument using IOTypes.Binary?  Can you give me some example code that passes original dicom file to the C++ module?

Thank you.

**Comment by thewtex** [comment]
Hello,

We are working on more examples, which should help.

The general flow you will want is:

[dcmjs](https://github.com/dcmjs-org/dcmjs) or [daikon](https://github.com/rii-mango/Daikon) for parsing metadata -> itk.js [`readImageFile`]( https://insightsoftwareconsortium.github.io/itk-js/) or [`readImageDICOMFileSeries`](https://insightsoftwareconsortium.github.io/itk-js/api/browser_io.html#readImageDICOMFileSeries-webWorker-fileList-gt-webWorker-image) to generate an itk.js [`Image`](https://insightsoftwareconsortium.github.io/itk-js/api/browser_io.html#readImageDICOMFileSeries-webWorker-fileList-gt-webWorker-image) -> process with [`runPipelineBrowser`](https://insightsoftwareconsortium.github.io/itk-js/api/browser_io.html#readImageDICOMFileSeries-webWorker-fileList-gt-webWorker-image) with `IOTypes.Image` -> convert the [itk.js Image to an vtk.js ImageData](https://kitware.github.io/vtk-js/api/Common_DataModel_ITKHelper.html) -> visualize in vtk.js

**Comment by EJShim** [comment]
Thank you for your comment. I think I can figure out parsing metadata using dcmjs or daikon.
