### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by ruanwenfeng** [InsightSoftwareConsortium/itk-js#239]
![image](https://user-images.githubusercontent.com/27943586/58784944-18cd7a80-8617-11e9-83db-c9f5177fe397.png)

**Comment by thewtex** [comment]
Can the input image be shared?

**Comment by ruanwenfeng** [comment]
@thewtex 
There will still be this error during development，but works after deploying to the production server.
dev:
   django python 3.6
pro:
   nginx django python 3.6

**Comment by thewtex** [comment]
@ruanwenfeng it sounds like it it is an issues with serving the static assets at the right location during development.
