### ISSUE TITLE
Documentation doesn't specify how to add web_target_link_libraries

### ISSUE THREAD

**Issue by swederik** [InsightSoftwareConsortium/itk-js#243]
Hello!

First off, thanks for the awesome work on this project.

One issue I had while starting off is that none of the examples seem to include `web_target_link_libraries` anywhere, so it was not immediately clear what I needed to do to set up a proper `CMakeLists.txt`. I ended up adding `target_link_libraries` in the wrong place until eventually finding the answer in one of the tests: https://github.com/InsightSoftwareConsortium/itk-js/blob/1fe62d437549e057de42b98fa70706cc96ec1d13/test/MedianFilterPipeline/CMakeLists.txt#L14-L21

I realize that this may be because I am not a C++ expert, but this feels like a missing piece in the documentation.

Would you accept a PR to add something like `NodeHelloInsight`, which would be essentially the same as `NodeHelloWorld`, but include `itkImage.h`. Basically just showing how to cross-compile this: https://itk.org/Wiki/ITK/HelloInsight

Here is what I was thinking: https://github.com/InsightSoftwareConsortium/itk-js/compare/master...swederik:node-hello-insight

I can add a docs page if you want and send a PR. Alternatively, we could change NodeHelloWorld instead.

Thanks!

**Comment by thewtex** [comment]
@swederik great point and suggestion -- yes a PR to clarify how to use `web_target_link_libraries` with the `NodeHelloInsight` example is welcome and appreciated! :+1:

**Comment by swederik** [comment]
Awesome, I'll send a PR when I get a chance.

**Comment by swederik** [comment]
And following https://github.com/InsightSoftwareConsortium/itk-js/issues/246 I guess we should also add a specific example for usage of VTK with ITK.

**Comment by thewtex** [comment]
Recent `itk.js` was improved so the regular `target_link_libraries` can be used -- `web_target_link_libraries` is no longer necessary.
