### ISSUE TITLE
Webworker results chrome out-of-memory crash

### ISSUE THREAD

**Issue by EJShim** [InsightSoftwareConsortium/itk-js#245]
Hello

I made a simple webworker pipeline using itk.js

it works fine mostly, but results chrome out-of-memory crash when trying to process

large data.

I tried to apply itk::ThresholdImageFilter on

512 x 512 x 210 sized image.
Image type is `int16_t`.

below is cxx pipeline code :

    //Define ITK Image Type
    using PixelType = int16_t;
    constexpr unsigned int Dimension = 3;
    using ImageType = itk::Image<PixelType, Dimension>;

    //Get Input
    using ReaderType = itk::ImageFileReader<ImageType>;
    auto reader = ReaderType::New();
    reader->SetFileName(argv[1]);

    int upper = 2000;

    itk::ThresholdImageFilter<ImageType>::Pointer upperThresholdFilter = itk::ThresholdImageFilter<ImageType>::New();
    upperThresholdFilter->SetInput(reader->GetOutput());
    upperThresholdFilter->ThresholdAbove(upper);
    upperThresholdFilter->SetOutsideValue(upper);
    //upperThresholdFilter->Update();

    //itkImage = upperThresholdFilter->GetOutput();

    using WriterType = itk::ImageFileWriter<ImageType>;
    auto writer = WriterType::New();
    writer->SetInput(upperThresholdFilter->GetOutput());
    writer->SetFileName(argv[2]);

    try{
        writer->Update();
    }catch(itk::ExceptionObject & error){
        std::cerr << "Error " << error << std::endl;
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}

`

I do not know much about webWorker or other web things.

Chrome develop console seems like it catches potential memory error when the worker tries to execute write() function in pipeline thread

![image](https://user-images.githubusercontent.com/8189976/60070376-5c685f80-9751-11e9-8437-28e06cdaf0c5.png)

I  am using the latest stable version of chrome browser. My desktop memory is 128GB.

Is this something that I can fix in code-level?

Thank you

**Comment by thewtex** [comment]
A few approaches to try:

- `//upperThresholdFilter->Update();` Yes, keep this commented and only call `->Update()` on the writer.
- Call [`ReleaseDataFlagOn()`](https://itk.org/Doxygen/html/classitk_1_1ProcessObject.html#ae732e9163879ae559ccd0b5957141f97) on the threshold filter and reader.
- Call [`SetNumberOfStreamDivisions`](https://itk.org/Doxygen/html/classitk_1_1ImageFileWriter.html#a3dc8330ca50ef60844a15c1a81cc6ade) on the writer to something like `6`.
- Call `.terminate()` on the web worker returned by `runPipeline` to release its memory.

**Comment by EJShim** [comment]
@thewtex  Thank you for your reply, I tried your approaches, but no differnece :(

I think the app is crashed before `runPipeline`  returns web worker, I think it is crashing somewhere in 
`writer->Update()`

**Comment by thewtex** [comment]
WebAssembly currently uses 32bit pointers, so there is a 4GB limit on the data, but we should not be hitting that yet, it this case.

Recently Chrome has some [memory management issues, especially when DevTools are open](https://bugs.chromium.org/p/chromium/issues/detail?id=935169). So, it is worth trying without DevTools open and on Firefox.

Also worth noting that the streaming approach only really helps when a streaming IO format is used, like MetaImage (.mha). Streaming in wasm pipelines could be improved by adding streaming support to the itk.js [itk::JSONImageIO](https://github.com/InsightSoftwareConsortium/itk-js/blob/master/include/itkJSONImageIO.h).

**Comment by thewtex** [comment]
@EJShim perhaps the arguments to `runPipelineBrowser` are not correct? What are these arguments?

**Comment by thewtex** [comment]
We have streaming support for `itk::JSONImageIO` in #334 -- please try streaming again and re-open if issues are still encountered.
