### ISSUE TITLE
Cannot find package "VTK"

### ISSUE THREAD

**Issue by EJShim** [InsightSoftwareConsortium/itk-js#246]
I am trying to build "WriteVTKPolyDataPipeline/" project,

When I execute `npx itk-js build .` ,

it says 

`  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake
`

There was no problem when I use ITK library in my project, and in ITK project, if I check CMakeCache.txt file, it shows

`VTK_DIR:PATH=/VTK-build`.

if I add `find_package(VTK REQUIRED)` it results the error.

**Comment by swederik** [comment]
I'm having the same issue. It looks like there is a specific image for this (kitware/itk-js-vtk) which should have VTK pre-installed.

https://github.com/InsightSoftwareConsortium/itk-js/tree/c85515eaa46736487f10d2ab3b87e6ad7286b13a/src/Docker/itk-js-vtk

but this doesn't seem to work for me: `npx itk-js build . --image kitware/itk-js-vtk:latest`

Oddly enough, just running `node build.js` from the top level directory does seem to work fine, and that script seems to be using the same image to build VTK stuff as well: https://github.com/InsightSoftwareConsortium/itk-js/blob/b20dcbe2a1a9ef3ea971690ff75141832434ffba/build.js#L220

**Comment by EJShim** [comment]
👍
