### ISSUE TITLE
Set vtkPolyData as a worker input?

### ISSUE THREAD

**Issue by EJShim** [InsightSoftwareConsortium/itk-js#254]
is it possible to set vtkPolyData as worker input?

I am trying to make a webworker for mesh processing that gets vtkPolyData as an input and vtkPolyData as an output.

```
        const args = ['thread.json', 'thread.json']
        const outputType = [
            {path : args[1], type : IOTypes.vtkPolyData},
        ];

        const inputs = [
            {path : args[0], type : IOTypes.vtkPolyData, data : this.selectedPolyData}
        ]


        
        const result = await runPipelineBrowser(null, 'meshProcessor', args, outputType, inputs);
        result.webWorker.terminate();
```

and it results error as below.

![image](https://user-images.githubusercontent.com/8189976/65941059-09dfc300-e465-11e9-869e-2f9e15e68dfb.png)

is it becasue of input type vtkPolyData?

**Comment by EJShim** [comment]
Or is there a way that I can convert a vtkPolydata into an itk.Mesh ??

**Comment by thewtex** [comment]
We currently need the relevant VTK C++ code. See:

  https://github.com/InsightSoftwareConsortium/itk-js/issues/187

**Comment by thewtex** [comment]
> Or is there a way that I can convert a vtkPolydata into an itk.Mesh ??

Not currently. This also requires the relevant C++ code. For itk.Mesh to vtkPolyData the code is:

https://github.com/InsightSoftwareConsortium/ITKVtkGlue/blob/master/include/itkMeshToVTKUnstructuredGridFilter.h

https://github.com/InsightSoftwareConsortium/itk-js/blob/master/src/Pipelines/MeshToPolyData/MeshToPolyData.cxx

**Comment by thewtex** [comment]
Closing so we can track this issue in one place at #187
