### ISSUE TITLE
vtk-js image to itk-js image conversion

### ISSUE THREAD

**Issue by boucaud** [InsightSoftwareConsortium/itk-js#260]
Hello,
Similar to vtk-js' ITKHelper.convertItkToVtkImage, I have a javascript function to convert vtk-js ImageData objects to itk-js images.
Do you think it would be useful to include it in this project ?

Adrien

**Comment by thewtex** [comment]
Hello Adrien,

Yes! A good place to put it may be `ITKHelper.convertVtkToItkImage`.

@hastingsgreer

**Comment by thewtex** [comment]
@boucaud well done! :clap:
