### ISSUE TITLE
Building full VTK using emscripten?

### ISSUE THREAD

**Issue by EJShim** [InsightSoftwareConsortium/itk-js#264]
There is an emscripten-built VTK in docker ```kitware/itk-js-vtk```, and seems it disabled rendering part of VTK.

I have been trying to build VTK using emscripten with rendering backend enabled, but no luck with executing web app. 

 VTK can be successfully built, but when I try to use ```vtkRenderWindow```, there errors occur. I found that vtk keeps trying to use OpenGL functions that are not existing in OpenGLES, such as ```glDrawBuffer```.

 There is a  emscripten-EGL example 
[https://github.com/EJShim/emscripten_EGL/blob/master/ref.cpp](https://github.com/EJShim/emscripten_EGL/blob/master/ref.cpp)
that uses EGL and X11 to display OpenGL Code in web. (gles3.0, webgl2.0)

So I built vtk using VTK_OPENGL_HAS_EGL=ON flag and tried to use ```vtkEGLRenderWindow```
but the app still trying to call ```glDrawBuffer()```  in ```vtkOpenGLRenderWindow``` class and results error.

I know I can simply use vtk.js , but I think there also might be a way to use c++ vtk to render WebGL.  Can you give me some clue to do this?

**Comment by thewtex** [comment]
VTK does need further patches to support rendering via Emscription.

**Comment by talhayranci** [comment]
Are there any new developments in this regard? @EJShim Have you tried compiling?

**Comment by jourdain** [comment]
We are waiting for a contribution which is supposed to happen soon.

**Comment by EJShim** [comment]
Haven't tried yet. I think if VTK does support GLES rendering such as android, it should also be possible rendering on web. I don't know which part of VTK should be updated: Raw VTK source code or CMake script.

**Comment by thewtex** [comment]
Updates to the `kitware/itk-js-vtk` Docker image are coming via #339 . We will add an example after the next release.

**Comment by EJShim** [comment]
@thewtex I tried to run Cone example, but having error when running, saying "wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'."

Thank you for your work anyway!

**Comment by EJShim** [comment]
@thewtex Is there a reason why antialiasing is disabled for SDL2OpenGLRenderWindow? I can see ` SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, 0);` from renderwindow, and `renderWindow->SetMultiSamples(0)` in the example code.

**Comment by martinken** [comment]
You should be able to set MultiSamples to 8 and it should work. SDL will be left as non multisampled which should be fine as the rendering all happens in a framebuffer which can be multisampled and then gets blitted into the SDL window

**Comment by EJShim** [comment]
`renderWindow->SetMultiSamples(8)`  does not change anything. I found `antialias:false` setting somewhere in emscripten output.js. `var EGL={errorCode:12288,defaultDisplayInitialized:false,currentContext:0,currentReadSurface:0,currentDrawSurface:0,contextAttributes:{alpha:false,depth:false,stencil:false,antialias:false}`

If I force to set {antialias:true} here, I get error saying 

`[.WebGL-0x7f866b50ce00]GL ERROR :GL_INVALID_OPERATION : glBlitFramebufferCHROMIUM: destination framebuffer is multisampled`

**Comment by EJShim** [comment]
If I compile below (only using gl and SDL) code and set antialias:true in webglContext, antialiasing can be enabled

`
#include <functional>
#include <emscripten.h>
#include <SDL.h>
#include <iostream>
#define GL_GLEXT_PROTOTYPES 1
#include <SDL_opengles2.h>

// Shader sources
const GLchar* vertexSource =
    "attribute vec4 position;                     \n"
    "void main()                                  \n"
    "{                                            \n"
    "  gl_Position = vec4(position.xyz, 1.0);     \n"
    "}                                            \n";


const GLchar* fragmentSource =
    "precision mediump float;\n"
    "void main()                                  \n"
    "{                                            \n"
    "  gl_FragColor[0] = gl_FragCoord.x/640.0;    \n"
    "  gl_FragColor[1] = gl_FragCoord.y/480.0;    \n"
    "  gl_FragColor[2] = 0.5;                     \n"
    "}                                            \n";


    
//Global Things...
SDL_Window *window;
GLfloat vertices[] = {0.0f, 0.5f, 0.5f, -0.5f, -0.5f, -0.5f};





// an example of something we will control from the javascript side
bool background_is_black = true;

// the function called by the javascript code
extern "C" void EMSCRIPTEN_KEEPALIVE toggle_background_color() { 
    background_is_black = !background_is_black;

}

extern "C" void EMSCRIPTEN_KEEPALIVE resize_window(){
    std::cout << "resize " << std::endl;

}




// std::function<void()> loop{}
void main_loop() {
    // move a vertex
    const uint32_t milliseconds_since_start = SDL_GetTicks();
    const uint32_t milliseconds_per_loop = 3000;
    vertices[0] = ( milliseconds_since_start % milliseconds_per_loop ) / float(milliseconds_per_loop) - 0.5f;
    glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);

    // Clear the screen
    if( background_is_black )
        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    else
        glClearColor(0.9f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);

    // Draw a triangle from the 3 vertices
    glDrawArrays(GL_TRIANGLES, 0, 3);

    SDL_GL_SwapWindow(window);

}

int main()
{
    SDL_CreateWindowAndRenderer(1000, 1000, 0, &window, nullptr);

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, 1);
    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, 2);

    // Create a Vertex Buffer Object and copy the vertex data to it
    GLuint vbo;
    glGenBuffers(1, &vbo);


    glBindBuffer(GL_ARRAY_BUFFER, vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);

    // Create and compile the vertex shader
    GLuint vertexShader = glCreateShader(GL_VERTEX_SHADER);
    glShaderSource(vertexShader, 1, &vertexSource, nullptr);
    glCompileShader(vertexShader);

    // Create and compile the fragment shader
    GLuint fragmentShader = glCreateShader(GL_FRAGMENT_SHADER);
    glShaderSource(fragmentShader, 1, &fragmentSource, nullptr);
    glCompileShader(fragmentShader);

    // Link the vertex and fragment shader into a shader program
    GLuint shaderProgram = glCreateProgram();
    glAttachShader(shaderProgram, vertexShader);
    glAttachShader(shaderProgram, fragmentShader);
    glLinkProgram(shaderProgram);
    glUseProgram(shaderProgram);

    // Specify the layout of the vertex data
    GLint posAttrib = glGetAttribLocation(shaderProgram, "position");
    glEnableVertexAttribArray(posAttrib);
    glVertexAttribPointer(posAttrib, 2, GL_FLOAT, GL_FALSE, 0, 0);


    emscripten_set_main_loop(main_loop, 0, true);

    return EXIT_SUCCESS;
}
`

**Comment by martinken** [comment]
I looked into it and SetMultiSample(8) doesn't work right now as the framebuffer is trying to use multisampled textures and gles 3.0 (and webgl2) doesn't support them. It does support multisampled renderbuffers so we can pretty easily modify the framebuffer creation to use renderbuffers instead of textures for multisampled gles. I'll give it a shot tomorrow.

**Comment by martinken** [comment]
OK I have it working with multisamples on both firefox/chrome. It required a couple changes but I'll try to get them merged soon.

**Comment by EJShim** [comment]
@martinken Another problem occurs when I try to volume rendering using SDL2OpenGLRenderWindow.

 it says :

````
Cone.js:2178 ERROR: In ../Rendering/OpenGL2/vtkShaderProgram.cxx, line 453

vtkShaderProgram (0xb4c220): ERROR: 0:498: '<=' : wrong operand types - no operation '<=' exists that takes a left-hand operand of type 'highp float' and a right operand of type 'const int' (or there is no acceptable conversion)

ERROR: In ../Rendering/VolumeOpenGL2/vtkOpenGLGPUVolumeRayCastMapper.cxx, line 2664

vtkOpenGLGPUVolumeRayCastMapper (0xb17f58): Shader failed to compile

[.WebGL-0x7fe7c15f9c00]GL ERROR :GL_INVALID_OPERATION : glTexImage3D: invalid internalformat/format/type combination GL_RGB/GL_RGB/GL_FLOAT

[.WebGL-0x7fe7c15f9c00]GL ERROR :GL_INVALID_OPERATION : glTexSubImage3D: level 0 does not exist
````

Can it also be resolved too? I am guessing currently VTK does not support volume rendering for GLES

**Comment by martinken** [comment]
Volume rendering doesn't work last I checked. I think it is all shader code issues due to some webgl glsl compilers being strict/bad. The first error is an easy fix and I fixed a few of them already.  But there are other issues. I think they can all be fixed and Sankhesh is going to take a look at some of them in a bit.

**Comment by martinken** [comment]
OK the multisample stuff is merged and should be working. Volume rendering is still an issue, feel free to open an issue on that. I just don't want this issue to be too broad. Thanks!

**Comment by EJShim** [comment]
@martinken Thank you for your work! I can see the antialiasing issue is resolved. But I found another problem occurs when I run [this](https://gitlab.kitware.com/vtk/vtk/-/tree/master/Examples/Emscripten/Cxx/ConeFullScreen) example.

I removed ```renderWindow->SetMultiSamples(0); ``` from the example code and the renderwindow goes somehow wrong..

**Comment by martinken** [comment]
Thanks, should be fixed in master now

**Comment by EJShim** [comment]
Seems like it is almost fully supported now in VTK.9.x
