### ISSUE TITLE
Add VTKExodusFileReader PolyDataIO

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/itk-js#276]
Add a PolyDataIO based on the `VTK::IOExodus`module:

 https://github.com/Kitware/VTK/tree/master/IO/Exodus

Steps (a [complete example can be found here](https://github.com/InsightSoftwareConsortium/itk-js/pull/273/commits/80cbae11beb7b00a53a8665f296bd3883fdbf2a5)):

0. [x] [Verify](https://insightsoftwareconsortium.github.io/itk-js/docs/hacking_itk_js.html) that the test suite runs and passes locally.
1. [x] Create *src/Bindings/VTKExodusFileReader.cxx*. This command line executable should accept the input filename as its first argument and the output filename as the second argument. It should use `vtkJSONDataSetWriter` to write the output.
2. [x] Add CMake configuration to build the command line executable at *src/Bindings/CMakeLists.txt*. Use this to build a native binary against a native VTK. Run it to verify that it behaves as expected.
3. [x] Upload a test dataset(s) to data.kitware.com and place their `*.sha512` file at *test/Input/*. Add the file path(s) to *test/CMakeList.txt*.
4. [x] Add `VTKExodusFileReader` to *src/PolyDataIOIndex.js*.
5. [x] Add `VTKExodusFileReader` to *CMakeLists.txt* `PolyDataIOPipelines` and set `polydataios_VTKExodusFileReader` to `vtkIOExodus`.
6. [x] Add a description of the new supported file format(s) in *doc/content/docs/polydata_formats.md*.
7. [x] Add new supported file extensions to *src/extensionToPolyDataIO.js*.
8. [x] Based on the output on the local filesystem with the native binary in the first step, add test(s) and define expected output in *test/readPolyDataLocalFileSyncTest.js*.
9. [x] Run `npm run build` and `npm run test`; fix issues identified.
10. [x] Create a  PR! :taco: :tada: :rocket: :woman_singer:

**Comment by vibraphone** [comment]
The Exodus reader has a lot of options for selecting what to load. What's done is a first pass. At some point, if itk-js provides a way for readers to expose options, the Exodus reader could certainly use it.

For example, many Exodus files have data for multiple timesteps... which one should be loaded. Similarly, element blocks and side sets tend to overlap each other – loading both would cause z-fighting (rendering artifacts). Being able to select a set would be nice. Note that a lot of these options involve users inspecting what is present in the file and then making a selection. That would mean running the reader multiple times with different arguments to get metadata (perhaps as field data?) and then to produce output.
