### ISSUE TITLE
IO modules get loaded multiple times

### ISSUE THREAD

**Issue by mhalle** [InsightSoftwareConsortium/itk-js#288]
The Webpack example appears to reload IO modules with every new file request;  I would guess this happens with other itk.js code as well.

itk version 10.2.1.

When I load a VTK file using the example, I see these requests being made to the web server:

127.0.0.1 - - [05/Jan/2020 00:35:15] "GET /itk/WebWorkers/MeshIO.worker.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Jan/2020 00:35:15] "GET /itk/MeshIOs/itkVTKPolyDataMeshIOJSBindingWasm.js HTTP/1.1" 200 -

If I load exactly the same VTK file again, I see the same JS files being re-requested from the server. Given that these IO modules are relatively heavy, it seems they shouldn't be getting re-loaded with every image or mesh load.  

Perhaps the lazy loader is not just lazy, but forgetful :)

**Comment by thewtex** [comment]
In the Webpack example, we could re-use the web worker or a service worker could be used to prevent fetching the IO modules, but the example is intended to keep it simple.

For a service worker example, see [itk-vtk-viewer](https://kitware.github.io/itk-vtk-viewer/index.html).
