### ISSUE TITLE
Improper orientation arrangement in readImageDICOMFileSeries

### ISSUE THREAD

**Issue by alfredomp** [InsightSoftwareConsortium/itk-js#291]
We found a DICOM image in ASL orientation that is not properly read by the readImageDICOMFileSeries. The output image is flipped in CORONAL and AXIAL directions. We didn't find the same issue reading the same ASL image but in nifti format. Additionally, we tested a DICOM image in LPS and the output image is correct.
We confirmed the flipping of the CORONAL and AXIAL directions by comparing the ouputs in 3D slicer and itkSnap.
Could it be that the readImageDICOMFileSeries has issues orienting some type of images, e.g., ASL?

**Comment by thewtex** [comment]
@alfredomp currently `readImageDICOMFileSeries` is using DCMTK as the backend to read the images -- 3D Slicer and ITK-SNAP use ITK/GDCM as the default. Slicer has an option to read with ITK/DCMTK -- is the same behavior observed with ITK/DCMTK in Slicer?

**Comment by thewtex** [comment]
Please try itk.js `12.1.0`.
