### ISSUE TITLE
Unpacking Image.data

### ISSUE THREAD

**Issue by Serhiy-Shekhovtsov** [InsightSoftwareConsortium/itk-js#296]
When reading a DICOM using one of [these methods](https://insightsoftwareconsortium.github.io/itk-js/api/browser_io.html) we get `itk/Image` object. But when trying to unpack the `Image.data` there is one problem - the `Image.size` stores indexes in ITK’s format (x,y,z) but the `Image.data` looks like a flatten multidimensional array that had indexes in order (z,x,y). So, in order to unpack it, you have to be aware of the history of these transformations and read it like this:

`var tensor = tf.tensor(image.data, [image.size[2], image.size[0], image.size[1]]);`

As you can see it's a bit confusing and requires some debugging, tweaking and looking into data to figure this out. Maybe you can add a property like `dataShape`, so reading will look like `tf.tensor(image.data, image.dataShape);`? Or reshape the array to `image.size` format before flattening.

But maybe I just missed something and there is another way to do it.

**Comment by thewtex** [comment]
This is an indexing convention difference between `itk` and `tf`. When using the data in `tf`, reverse the `Image.size`. This could be a common stumbling block -- please take a look at #297, which adds more documentation.
