### ISSUE TITLE
building ITK with emscripten

### ISSUE THREAD

**Issue by prashanthdumpuri** [InsightSoftwareConsortium/itk-js#320]
Can someone please help me build ITK using emscripten on Windows 10?  have built ITK using CMake and Visual studio but 'am struggling with emcsripten. 

Brief background about why I need it: I need to use emscripten because I have to run my ITK filters from a web browser. So, I have to build ITK and my ITK filters using emscripten and then convert them to WASM. I do not know javascript programming and cannot use itk-js.

I downloaded emsdk from [here](https://github.com/emscripten-core/emsdk) and 'am using ITK-4.9.0. I'm using the following cmake command:

`cmake -DCMAKE_TOOLCHAIN_FILE=Emscripten.cmake -G Ninja -DCMAKE_CXX_FLAGS=“-Wno-warn-absolute-paths --memory-init-file 0 -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -D_LARGEFILE64_SOURCE=1” -DCMAKE_C_FLAGS=“-Wno-warn-absolute-paths --memory-init-file 0 -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -D_LARGEFILE64_SOURCE=1” -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF`

Configuring works fine but I get errors when building ITKHDF5. The error I see on screen says
_ninja build stopped subcommand failed_ and I do not see anything in CMakeError.log that says an error. Ninja is new to me as well. Can someone please help me how to debug this error message? Or better yet, can someone please give me instructions on how to build ITK using emscripten?

Thanks

**Comment by thewtex** [comment]
itk.js provides ITK built with Emscripten. To use WASM, JavaScript is required, but it is not that hard.

Please take a look at the documentation:

https://insightsoftwareconsortium.github.io/itk-js/examples/hello_world_node.html
