### ISSUE TITLE
Read MetaImage using Web Browser IO

### ISSUE THREAD

**Issue by Serhiy-Shekhovtsov** [InsightSoftwareConsortium/itk-js#323]
Is there any way to load the image saved in MetaImage format using itk-js Browser IO? I can see it listed [here](https://github.com/InsightSoftwareConsortium/itk-js/blob/336b98ac89694f853b1fa936ac4bf337331ea980/doc/content/docs/image_formats.md), but can't find any example. Is it's only supported for Node.js environment?

**Comment by thewtex** [comment]
Yes, MetaImage is well supported.

Example:

https://kitware.github.io/itk-vtk-viewer/app/?fileToLoad=https://data.kitware.com/api/v1/file/5c588a698d777f072b2a8281/download/cthead1.mha

See [`readImageFile`](https://insightsoftwareconsortium.github.io/itk-js/api/browser_io.html#readImageFile-webWorker-file-gt-webWorker-image).

Example:

https://glitch.com/~itk-js-umd-example

**Comment by Serhiy-Shekhovtsov** [comment]
@thewtex thanks for this example! I have a bit different problem, however. Trying to read files saved as mhd+raw pair. But figured a way to read them using Node.js and save as JSON+data. And then use new pair in the web version.

**Comment by thewtex** [comment]
@Serhiy-Shekhovtsov :+1: sounds like a good approach.
