### ISSUE TITLE
Build itk

### ISSUE THREAD

**Issue by Timanu05** [InsightSoftwareConsortium/itk-js#357]
Hi, I try to modify the meshToPolyData.cxx script to be able to read an UnstructuredGrid with the vtkUnstructuredGridReader output. When I build itk.js, I can't find my meshToPolyData.js as I do when I npm install itk.js. Do I need to build it like the hello world example ? If so do I need to install and specify ITK and VTK library on my computer ?

Thanks for your help.

**Comment by thewtex** [comment]
Hi @Timanu05 , a few pointers

- itk.js [ships](https://github.com/InsightSoftwareConsortium/itk-js/blob/0afbb3d1fdc13b7f200310a5f7a6780983d48876/test/readPolyDataLocalFileSyncTest.js#L28-L70). with functionality to convert an UnstructuredGrid to a vtk.js PolyData with `vtkUnstructuredGridReader`. Use the [`readPolyData*` functions](https://insightsoftwareconsortium.github.io/itk-js/api/browser_io.html#readPolyDataFile-webWorker-file-gt-webWorker-polyData).
- If you want to build a custom pipeline that uses VTK C++ and ITK C++, use the `kitware/itk-js-vtk` image when invoking the `itk-js` cli, i.e.,

```
itk-js build --image kitware/itk-js-vtk mySourceDir
```

This image contains a pre-built version of VTK C++ and ITK C++ already inside the Docker image.

**Comment by Timanu05** [comment]
Thanks for your answer. When I use the readPolyDataFile function with a .vtu file in input, I've got a "Cannot read property '0' of undefined" error from outputs[0] in the function.

Also I notice that for .vtr files I've got a " Could not find IO for xxxxxx.vtr". Is there a way to read .vtr files with itk.js ?

**Comment by thewtex** [comment]
If you click on this page:

https://kitware.github.io/itk-vtk-viewer/app/

and select the file, does it read and render?


We could add support for .vtr similar to .vtu. See:

https://github.com/InsightSoftwareConsortium/itk-js/issues/275

**Comment by Timanu05** [comment]
Yes it loads my vtu but not my vtr, I must have missed something in the code. I'll look into that for my vtu thanks you !

**Comment by thewtex** [comment]
vtr support is added in https://github.com/InsightSoftwareConsortium/itk-js/pull/358
