### ISSUE TITLE
readDICOMImageSeries failed under history mode of Vue

### ISSUE THREAD

**Issue by lihouxing-sjtu** [InsightSoftwareConsortium/itk-js#378]
Hi,
I am having some trouble of read dicom series under the history mode of vue. 
The problem is that, when I use readDICOMImageSeries for example  with the url

1.  **http://localhost:8080/preTag/readdicomseries/** . Failed
![image](https://user-images.githubusercontent.com/18169068/95878004-4f88d880-0da7-11eb-9cab-dadb33e1c266.png)

2.  **http://localhost:8080/readdicomseries/postTag** Failed
![image](https://user-images.githubusercontent.com/18169068/95877196-709cf980-0da6-11eb-9383-9b285f806059.png)

it looks the ImageIO.worker.js at the wrong url address, and the correct one should be **http://localhost:8080/itk/WebWorkers/ImageIO.worker.js**

No error would occur if I use hash mode or under the url **http://localhost:8080/readdicomseries/**

Many thanks for any advice!

**Comment by thewtex** [comment]
Hi @lihouxing-sjtu ,

To change where it looks for the webworkers and WASM files, there is documentation here:

https://insightsoftwareconsortium.github.io/itk-js/examples/

The relevant sections are

- Vue.js
- Webpack
- Unpkg / CDN

HTH,
Matt

**Comment by lihouxing-sjtu** [comment]
Hi @thewtex,
Thanks! You really saved my life !
I managed to fix this by setting itkConfig.
For those who also confronts the same issue, my reference code is shown blow:
in my vue.config.js and under the section of configureWebpack
`
resolve: {
        alias: {
          './itkConfig$': path.resolve(__dirname, 'itkConfig.js'), 
        },
      },
`


in  itkConfig.js:
`
const itkConfig = {  
    itkModulesPath:  '/itk'
}
export default itkConfig
`
