### ISSUE TITLE
`FS error` on `readImageBlob`

### ISSUE THREAD

**Issue by FezVrasta** [InsightSoftwareConsortium/itk-js#384]
Hi, I'm trying to load a `.nrrd` file retrieved from the Koa endpoint below:

```js
router.get('/api/nrrd/:pathname', async (ctx) => {
  // files = list of DCM files that load fine on other viewers
  const image = await readImageLocalDICOMFileSeries(files);
  const tempFile = `${tmp.tmpNameSync()}.nrrd`;
  await writeImageLocalFile(true, image, tempFile);
  const stream = createReadStream(tempFile);
  ctx.attachment(`${pathname}.nrrd`);
  ctx.type = 'application/octet-stream';
  ctx.body = stream;
});
```

My client reads it with:

```js
const res = await fetch('/api/nrrd/test');
const blob = await res.blob();
const { image } = await readImageBlob(null, blob, `test.nrrd`);
```

But with the code above I get the `FS error` error.

```
Uncaught (in promise) {message: "FS error", stack: "<generic error, no stack>"}
```

May someone tell me what am I doing wrong? I think I tried most of the `read*` functions...

**Comment by thewtex** [comment]
@FezVrasta the itk.js calls look correct :eyes: . Is the blob content the same as when `test.nrrd` is input as a `File` in the browser?

**Comment by FezVrasta** [comment]
I'm sorry, I didn't manage to retrieve a nrrd file without sensitive data so right now I'm unable to share anything with you. I'll get back to you once and if I'll get access to a good one.
