### ISSUE TITLE
SSRF vulnerability in axios version < 0.21.1

### ISSUE THREAD

**Issue by scottwittenburg** [InsightSoftwareConsortium/itk-js#391]
Our project has a transitive dependency on `axios` via this project.  A couple days ago, we started seeing high severity dependabot alert regarding axios versions `< 0.21.1`.

I can make a PR simply updating the version, but as a lot of folks have started moving to the latest version of `axios`, at least one report came in about some features maybe not working the same after moving from `0.19` to `0.21`.  I have no idea whether this project would be affected by that, or if transition would be smooth.

Here's the original `axios` [issue](https://github.com/axios/axios/issues/3407), and a link to the more recent [issue](https://github.com/axios/axios/issues/3526) created after people started picking up the fix.  

Please let me know what I can do to help.

**Comment by thewtex** [comment]
Released in in `13.3.1`
